default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] || 'codice_fiscale_app_development' %>
