default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: admin
  password: admin
  host: localhost

development:
  <<: *default
  database: codice_fiscale_app_development

test:
  <<: *default
  database: codice_fiscale_app_test

production:
  <<: *default
  database: codice_fiscale_app_prod
